version: '3.9'
services:
  ui:
    hostname: ui
    build: ./ui
    restart: always
    ports:
      - '3000:3000'
      - '9230:9230'
    volumes:
      - /app/node_modules
      - ./ui:/app
    command: npm run dev
  server:
    hostname: server
    build: ./server
    restart: always
    ports:
      - "5000:5000"
      - "9229:9229"
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      DB_CONNECT_MONGOOSE: "mongodb://root:example@mongo:27017/good_deals?authSource=admin"
    command: npm run start
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: good_deals
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db
      - ./server/mongo_init_script/:/docker-entrypoint-initdb.d/:ro

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017

volumes:
  mongodata:
